### ISSUE TITLE
Multi-Cal events not showing at the top

### ISSUE THREAD

**Issue by ryansowinski** [yaylinda/scriptable#9] opened 2021-04-02 20:53 UTC
I use both your single and multiple day calendars. The single works fine, but the multiple day calendar won’t show current ongoing events.
As in, if there are events from 10-12 and it is 10:30, it won’t show at all, on any day.
But everything else shows fine.
Also, everything does show if I change the start time from -1 to any other number.
So I assume the issue is in the current time function.

**Comment by yaylinda** [comment] 2021-09-19 21:56
Ohh thanks for raising the issue! If you have the fix, would you mind sending a PR?

**Comment by ryansowinski** [comment] 2021-09-19 23:31
I do not. I haven’t been able to get back around to it to figure out

**Comment by yaylinda** [comment] 2022-04-19 09:13
Hi there! It has been a while. Were you able to find the root cause for this? If so, please submit a PR! Otherwise, I will be closing out the issue for now :). Feel free to open it back up, if needed!

**Closed by yaylinda** 2022-04-19 09:13 UTC

**Comment by ryansowinski** [comment] 2022-04-22 16:21
No, I have not. I have tried messing with the coding a little but, I'm definitely not adept enough with this.
